- libraries/_template/pyproject.toml
- libraries/dagster-contrib-modal/pyproject.toml
- libraries/dagster-hex/pyproject.toml
- libraries/dagster-hex/uv.lock
- libraries/dagster-hightouch/pyproject.toml
- libraries/dagster-hightouch/uv.lock
- Required for build-time dependency
> maint: add build system configuration to pyproject.toml

- libraries/pipes/implementations/java/dagster-pipes-java/src/main/java/pipes/PipesContext.java
- libraries/pipes/implementations/java/dagster-pipes-java/src/main/java/pipes/utils/MetadataBuilder.java
- libraries/pipes/implementations/java/dagster-pipes-java/src/main/java/pipes/utils/PipesUtils.java
Refactored metadata resolving in PipesContext methods
> Refactored metadata resolving in PipesContext methods

- libraries/pipes/implementations/rust/README.md
- Updating README and validating CI is triggered
- N/A
> [dagster-pipes-rust] update readme on how to generate quicktypes

- .github/workflows/libraries-pipes-java.yml
- .github/workflows/libraries-pipes-rust.yml
> [pipes] run CI against Pipes tests changes

- libraries/pipes/implementations/rust/CHANGELOG.md
- libraries/pipes/implementations/rust/Cargo.toml
Update version and change log in preparation of 0.1.7 publish.
> [dagster-pipes-rust] publish 0.1.7

- README.md
- Highlights contributors directly in README
> Adds community callout to README

- libraries/dagster-notdiamond/examples/example_book_reviews_summary_proxying.py
> [dagster-notdiamond] adds example of using the model gateway

- libraries/dagster-hex/CHANGELOG.md
- libraries/dagster-hex/pyproject.toml
- libraries/dagster-hex/uv.lock
> [dagster-hex] release 0.1.5

- libraries/dagster-iceberg/kitchen_sink.py
Create a basic kitchen sink project to test Iceberg I/O managers
Local execution
> [dagster-iceberg] Create minimal `kitchen_sink.py`

- .github/workflows/quality-check-dagster-iceberg.yml
- libraries/dagster-iceberg/Makefile
- libraries/dagster-iceberg/kitchen-sink/Makefile
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
- libraries/dagster-iceberg/pyproject.toml
- libraries/dagster-iceberg/uv.lock
Run end-to-end tests in CI. Also, standardize CI and Makefile configuration.
CI (and local CI)
> [dagster-iceberg] Add end-to-end kitchen sink test

- libraries/dagster-iceberg/README.md
I deployed the dagster-iceberg documentation on my fork of this repository, and updated the README accordingly.
-
> [dagster-iceberg] Update links in documentation

- libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
Test the flip side of the I/O manager.
CI and local CI.
> [dagster-iceberg] Test reloading data from Iceberg

- libraries/dagster-qdrant/Makefile
- libraries/dagster-qdrant/README.md
- libraries/dagster-qdrant/dagster_qdrant/__init__.py
- libraries/dagster-qdrant/dagster_qdrant/config.py
- libraries/dagster-qdrant/dagster_qdrant/resource.py
- libraries/dagster-qdrant/dagster_qdrant_tests/test_resource.py
- libraries/dagster-qdrant/pyproject.toml
- libraries/dagster-qdrant/uv.lock
Hey 👋. Greetings from [Qdrant](https://qdrant.tech).
This PR introduces a new `dagster-qdrant` package to add support for integrating Qdrant in Dagster workflows.
Associated tests and documentation updates(https://github.com/dagster-io/dagster/pull/28247) are included.
> feat: dagster-qdrant

- RELEASES.md
- libraries/dagster-anthropic/pyproject.toml
- libraries/dagster-gemini/pyproject.toml
- libraries/dagster-hex/pyproject.toml
- libraries/dagster-iceberg/pyproject.toml
- libraries/dagster-notdiamond/pyproject.toml
- release.sh
Used in:
- **Release dagster-anthropic 0.0.2**
- **Release dagster-gemini 0.0.2**
- **Release dagster-hex 0.1.7**
- **Release dagster-iceberg 0.2.2**
- **Release dagster-notdiamond 0.1.3**
> Adds release.sh and updates RELEASES.md

- libraries/dagster-iceberg/kitchen-sink/Makefile
- libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
- libraries/dagster-iceberg/pyproject.toml
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
- libraries/dagster-iceberg/uv.lock
Add a very basic I/O manager implementation. This doesn't handle edge cases, partitioning, existing tables—all to come!
Manually using the kitchen sink environment; see https://dagsterlabs.slack.com/archives/C08CXRWRBJR/p1741202970489739
I split out the test PR, because they're failing due to some environment issues.
> [dagster-iceberg] Create a `SparkIcebergIOManager`

- libraries/dagster-iceberg/kitchen-sink/Dockerfile
- libraries/dagster-iceberg/kitchen-sink/Makefile
- libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
- libraries/dagster-iceberg/uv.lock
Make sure Spark Iceberg I/O manager is tested in CI.
CI? (Local CI using `act` also works!)
> [dagster-iceberg] Test end-to-end Spark read/write

- libraries/_template/example_integration/__init__.py
- libraries/dagster-anthropic/dagster_anthropic/__init__.py
- libraries/dagster-chroma/dagster_chroma/__init__.py
- libraries/dagster-contrib-gcp/dagster_contrib_gcp/__init__.py
- libraries/dagster-gemini/dagster_gemini/__init__.py
- libraries/dagster-hex/dagster_hex/__init__.py
- libraries/dagster-hightouch/dagster_hightouch/__init__.py
- libraries/dagster-iceberg/src/dagster_iceberg/__init__.py
- libraries/dagster-modal/dagster_modal/__init__.py
- libraries/dagster-notdiamond/dagster_notdiamond/__init__.py
- libraries/dagster-obstore/dagster_obstore/__init__.py
- libraries/dagster-qdrant/dagster_qdrant/__init__.py
- libraries/dagster-teradata/dagster_teradata/__init__.py
- libraries/dagster-weaviate/dagster_weaviate/__init__.py
Community integrations don't currently show up in telemetry.
Existing tests pass; registration isn't tested.
> Enable telemetry across all community integrations

- libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
Ruff cleared my print statement, so I'm putting it back.
Manually.
> [dagster-iceberg] Restore `print` of reloaded data

- libraries/dagster-iceberg/src/dagster_iceberg/_utils/io.py
- libraries/dagster-iceberg/src/dagster_iceberg/_utils/partitions.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Same as https://github.com/dagster-io/dagster/pull/28909
CI
> [dagster-iceberg] Drop an unnecessary length check

- libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
Add an e2e test for time partitions (so we're not only testing multi-dimensional partitioning with a time partition).
Manual run and CI.
> [dagster-iceberg] Test time partitions with Polars

- libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
- libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Want to add some time partitioning examples, but we'll start with multi-dimensional partitioning, because the data is naturally partitioned (`part.0`, `part.1`) to begin with.
Manually and in CI (updated e2e test).
> [dagster-iceberg] Test 2D partitioning with Polars

- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py
> [dagster-iceberg] Standardize capitalization of IO

- .github/workflows/quality-check-dagster-evidence.yml
- .github/workflows/release-dagster-evidence.yml
- libraries/dagster-evidence/Makefile
- libraries/dagster-evidence/README.md
- libraries/dagster-evidence/dagster_evidence/__init__.py
- libraries/dagster-evidence/dagster_evidence/lib/__init__.py
- libraries/dagster-evidence/dagster_evidence/lib/evidence_project.py
- libraries/dagster-evidence/dagster_evidence_tests/test_dagster_evidence.py
- libraries/dagster-evidence/dagster_evidence_tests/test_version.py
- libraries/dagster-evidence/pyproject.toml
- libraries/dagster-evidence/uv.lock
Adds a Dagster Component for `evidence.dev`
Factored this out of a monolithic project based on the tutorial. Not sure what the best way to test this is!
> RFC: dagster-evidence

- libraries/dagster-iceberg/pyproject.toml
- libraries/dagster-iceberg/tests/conftest.py
- libraries/dagster-iceberg/tests/docker/Dockerfile
- libraries/dagster-iceberg/tests/docker/compose.yaml
- libraries/dagster-iceberg/tests/docker/entrypoint.sh
- libraries/dagster-iceberg/tests/docker/spark-defaults.conf
- libraries/dagster-iceberg/tests/io_managers/test_spark_io_manager.py
- libraries/dagster-iceberg/uv.lock
My goal was to use a consistent environment for unit tests (i.e. use a PostgreSQL catalog with the Spark Iceberg environment, since the existing tests were already using a Dockerized PostgreSQL catalog.
Unfortunately, I wasn't able to get it to work using `testcontainers`—I put some effort into using `ComposeContainer` to no avail—so I switched to a plain Docker-compose based setup and made sure things still work.
CI, local CI
> [dagster-iceberg] Set up Spark Iceberg Compose env

- libraries/dagster-iceberg/pyproject.toml
- libraries/dagster-iceberg/tests/conftest.py
- libraries/dagster-iceberg/tests/docker/Dockerfile
- libraries/dagster-iceberg/tests/docker/compose.yaml
- libraries/dagster-iceberg/tests/docker/entrypoint.sh
- libraries/dagster-iceberg/tests/docker/spark-defaults.conf
- libraries/dagster-iceberg/tests/io_managers/test_arrow_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_daft_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_pandas_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_polars_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_spark_io_manager.py
- libraries/dagster-iceberg/uv.lock
Remove dead code.
CI, local CI
> [dagster-iceberg] Kill unused `CustomDbIOManager`s

- libraries/dagster-iceberg/tests/io_managers/test_spark_io_manager.py
- Test Spark with hourly partitions
- Refactor some test code into `_exec_in_container` function
- Locally using `act`
> [dagster-iceberg] Test Spark with hourly partition

- libraries/dagster-iceberg/tests/io_managers/test_arrow_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_daft_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_pandas_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_polars_io_manager.py
- libraries/dagster-iceberg/tests/io_managers/test_spark_io_manager.py
- Test Spark with daily partitions
- Locally using `act`
> [dagster-iceberg] Test Spark with daily partitions

- libraries/dagster-iceberg/tests/io_managers/test_spark_io_manager.py
- Test Spark with daily partitions
- Locally using `act`
> [dagster-iceberg] Test Spark with multi partitions

- libraries/dagster-iceberg/src/dagster_iceberg/config.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/arrow.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/daft.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/pandas.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/polars.py
- libraries/dagster-iceberg/src/dagster_iceberg/resource.py
Make docstrings compatible with Sphinx `autodoc`, used to build Dagster docs.
Ran `yarn build-api-docs` until it worked:
> [dagster-iceberg] Make docs build for Dagster site

- libraries/dagster-iceberg/src/dagster_iceberg/handler.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/polars.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Trivial improvement. Soft dependency on https://github.com/dagster-io/dagster/pull/29738.
> [dagster-iceberg] Remove pandas for Polars example

- libraries/dagster-iceberg/src/dagster_iceberg/_utils/partitions.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py
- libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
- Similar to the previous PR, but more cases
-
> less specific import

- libraries/dagster-teradata/pyproject.toml
> dagster-teradata: added missing packages

- libraries/dagster-ducklake/README.md
- libraries/dagster-ducklake/dagster_ducklake/Makefile
- libraries/dagster-ducklake/dagster_ducklake/__init__.py
- libraries/dagster-ducklake/dagster_ducklake/duckdb_file.py
- libraries/dagster-ducklake/dagster_ducklake/duckdb_protocol.py
- libraries/dagster-ducklake/dagster_ducklake/ducklake.py
- libraries/dagster-ducklake/dagster_ducklake_tests/test_ducklake.py
- libraries/dagster-ducklake/pyproject.toml
- libraries/dagster-ducklake/uv.lock
- as part of https://georgheiler.com/event/tdwi-25-roundtable-nuernberg/ add integration of ducklake with dagster
- in use at https://ascii.ac.at/
feat: add ducklake integration for various ducklake backends
> feat: add ducklake integration
