libraries/dagster-contrib-modal/CHANGELOG.md, libraries/dagster-contrib-modal/dagster_contrib_modal/resources.py, libraries/dagster-contrib-modal/pyproject.toml, libraries/dagster-contrib-modal/uv.lock
`context` parameter should be a union of op execution and asset execution context.
=> [dagster-contrib-modal] support AssetExecutionContext in pipes run

.github/CODEOWNERS, .github/workflows/libraries-pipes-rust.yml, libraries/pipes/implementations/rust/README.md
- Moves the GitHub actions original in the `dagster-pipes-rust` repo
- Sets codeowners for `libraries/pipes/implementations/rust`
- Observe CI
=> [dagster-pipes-rust] set codeowners

libraries/pipes/implementations/rust/example-dagster-pipes-rust-project/rust_processing_jobs/src/main.rs
Makes the creation of the metadata a little bit less verbose and consistent with the other invocation
Tests
=> [pipes-rust] - use ::new to create the metadata value

libraries/pipes/jsonschema/PipesContextData.schema.json, libraries/pipes/jsonschema/PipesException.schema.json
Remove `null` type from any optional field in the object that wasn't specific in the `required` attribute. ~And fix `quicktype.sh` shebang from `#!bash` to `#!/bin/bash` to fix script broken on macOS.~
~- Run `quicktype.sh` and expected no changes in `types.rs`.~
=> [jsonschema] improve jsonschema optional fields

libraries/pipes/implementations/rust/src/context_loader.rs, libraries/pipes/implementations/rust/src/lib.rs, libraries/pipes/implementations/rust/src/params_loader.rs, libraries/pipes/implementations/rust/src/writer/message_writer.rs
It's not clear what's types are publiclly exposed. Exposing too much may lead to unnecessary breaking changes in the future. 
As such, public re-exports (`pub use ...`) are grouped separately in `lib.rs`. 
I also took this chance to improve the docs for public facing types and traits. 
With changes here and from #61, here's the exposed surface area:
- cargo tests and manually running `dagster dev`.
=> [dagster-pipes-rust] 📝 Sort exports and update docs for public-facing traits

libraries/pipes/tests/dagster-pipes-tests/src/dagster_pipes_tests/suite.py
This asserts that all log levels are logged at least once by the external pipes process. Without this, an implementation would have the test succeeding if no log levels are actually logged.
Ran the log tests in the runs implementation after this change and observed the test failing
=> [dagster-pipes-tests] - assert that all levels are logged at least once

libraries/pipes/tests/dagster-pipes-tests/src/dagster_pipes_tests/suite.py
This makes sure the asset check tests are skipped if `report_asset_check` is set to false in `pipes.toml`
Ran `uv run pytest` in the rust implementation with the flag turned to true / false and observed the expected behavior: tests are skipped when set to false and run when set to true
=> [dagster-pipes-tests] - Fixes asset check skip flag

libraries/pipes/implementations/java/dagster-pipes-java/src/test/java/pipes/MainTest.java, libraries/pipes/implementations/rust/src/bin/pipes_tests.rs, libraries/pipes/tests/dagster-pipes-tests/src/dagster_pipes_tests/suite.py
Currently, the job name flag use camel case while other flags use kebab case. This changeset convert the `jobName` into `job-name` to make it consistent with other flags and change the Java implementation to use that flag instead.
Make java implementation tests passed by running `uv run pytest` in java directory.
=> [dagster-pipes-test] make job name flag consistent with other flags

libraries/pipes/tests/dagster-pipes-tests/src/dagster_pipes_tests/suite.py
I found during run pytest that `context.dagster_run` is deprecated and will be remove in the future. This PR migrate those calls to use `context.run` instead.
-
=> [dagster-pipes-test] use context.run to get job_name

libraries/pipes/implementations/rust/CHANGELOG.md, libraries/pipes/implementations/rust/example-dagster-pipes-rust-project/rust_processing_jobs/src/main.rs, libraries/pipes/implementations/rust/src/lib.rs
This adds the `data_version` parameter to `report_asset_materialization` and makes sure it is part of the pipes message.
Updated test
=> [dagster-pipes-rust] - Expose data version in report_asset_materialization

libraries/dagster-contrib-gcp/README.md, libraries/dagster-contrib-gcp/dagster_contrib_gcp/cloud_run/run_launcher.py, libraries/dagster-contrib-gcp/dagster_contrib_gcp_tests/cloud_run_tests/conftest.py, libraries/dagster-contrib-gcp/dagster_contrib_gcp_tests/cloud_run_tests/test_run_launcher.py, libraries/dagster-contrib-gcp/uv.lock
Adds job timeout as dagster.yaml instance config. Also adds some basic docs for the Cloud Run run launcher.
Ensure that Cloud Run run worker timeout is configurable at the instance level.
Unit tests have been updated.
=> fix: add cloud run job timeout to instance config

libraries/pipes/implementations/java/dagster-pipes-java/src/main/java/pipes/utils/Example.java, libraries/pipes/implementations/java/dagster-pipes-java/src/test/java/pipes/MainTest.java, libraries/pipes/implementations/java/dagster-pipes-java/src/test/java/pipes/PipesTests.java
- Java tests refactoring
- uv run pytest
=> Java tests refactoring

.github/workflows/quality-check-dagster-contrib-gemini.yml, .github/workflows/release-dagster-contrib-gemini.yml, libraries/dagster-contrib-gemini/Makefile, libraries/dagster-contrib-gemini/README.md, libraries/dagster-contrib-gemini/dagster_contrib_gemini/__init__.py, libraries/dagster-contrib-gemini/dagster_contrib_gemini/resource.py, libraries/dagster-contrib-gemini/dagster_contrib_gemini_tests/test_resource.py, libraries/dagster-contrib-gemini/pyproject.toml, libraries/dagster-contrib-gemini/uv.lock
- This PR adds support for the GeminiResource. In addition to wrapping the Gemini client ("GenerativeModel"), the resource will also automatically log usage-metadata (calls and tokens) to the AssetMetadata.
- Created mock-tests - testing both the get_model functionality, and the wrapping of the Gemini.generate_content call for metadata-logging (following as closely as possible the example of dagster-openai tests).
- Tested the resource against the real Gemini API, making sure that the usage stats are logged to the AssetMetadata. 
=> Add Gemini Resource

.github/workflows/quality-check-dagster-contrib-chroma.yml, .github/workflows/release-dagster-contrib-chroma.yml, libraries/dagster-contrib-chroma/Makefile, libraries/dagster-contrib-chroma/README.md, libraries/dagster-contrib-chroma/dagster_contrib_chroma/__init__.py, libraries/dagster-contrib-chroma/dagster_contrib_chroma/config.py, libraries/dagster-contrib-chroma/dagster_contrib_chroma/resource.py, libraries/dagster-contrib-chroma/dagster_contrib_chroma_tests/test_resource.py, libraries/dagster-contrib-chroma/pyproject.toml, libraries/dagster-contrib-chroma/uv.lock
- An integration of dagster with [Chroma](https://www.trychroma.com/) - supports both local and HTTP Chroma databases.
- Added unit-tests that create a local (filesystem) Chroma instance, and use the ChromaResource (LocalConfig) to query it.
- Added unit-tests that create a local HTTP Chroma instance, and use the ChromaResource to query it via HTTP.
=> Add Chroma Resource

libraries/dagster-obstore/pyproject.toml
Setuptools requires you to be more explicit, which I forgot to set anything. The 0.1.0 release was therefore an empty wheel. Switched to hatchling instead which is more convenient
uv build and checked the contents ; )
=> fix: release, use hatchling build system

.github/workflows/template-quality-check.yml, libraries/dagster-chroma/dagster_chroma/resource.py, libraries/dagster-notdiamond/examples/example_book_reviews_summary_proxying.py, libraries/dagster-sdf/dagster_sdf/__init__.py, libraries/dagster-sdf/dagster_sdf/asset_decorator.py, libraries/dagster-sdf/dagster_sdf/asset_utils.py, libraries/dagster-sdf/dagster_sdf/cli/app.py, libraries/dagster-sdf/dagster_sdf/dagster_sdf_translator.py, libraries/dagster-sdf/dagster_sdf/resource.py, libraries/dagster-sdf/dagster_sdf/sdf_cli_event.py, libraries/dagster-sdf/dagster_sdf/sdf_cli_invocation.py, libraries/dagster-sdf/dagster_sdf/sdf_event_iterator.py, libraries/dagster-sdf/dagster_sdf/sdf_information_schema.py, libraries/dagster-sdf/dagster_sdf/sdf_workspace.py, libraries/dagster-sdf/dagster_sdf_tests/cli/test_scaffold.py, libraries/dagster-sdf/dagster_sdf_tests/conftest.py, libraries/dagster-sdf/dagster_sdf_tests/test_asset_checks.py, libraries/dagster-sdf/dagster_sdf_tests/test_asset_decorator.py, libraries/dagster-sdf/dagster_sdf_tests/test_code_references.py, libraries/dagster-sdf/dagster_sdf_tests/test_resource.py, libraries/dagster-sdf/dagster_sdf_tests/test_sdf_workspace.py, libraries/dagster-sdf/dagster_sdf_tests/test_table_metadata.py
Add Ruff formatter to the template, to:
1. Catch formatting errors in CI
2. Be able to use the template for `dagster-iceberg`
First local CI, then CI
Locally, I get some other (unrelated) failures:
* `dagster-hightouch` (typing error with `NamedTuple`)
* `dagster-obstore-template` fails for me (no Docker Compose config)
* `dagster-sdf` (can't find executable)
=> Add Ruff formatter check to quality check template

.github/workflows/quality-check-dagster-teradata.yml, .github/workflows/template-quality-check.yml, libraries/dagster-teradata/dagster_teradata/resources.py
Was trying to bring `dagster-teradata` in line with the rest/using the same template, but not going to bother for now since the functional tests don't pass/would require passing an arg to `pytest`. However, I did find that there was a formatting issue not being caught, since the updated template isn't being used.
Nit: Also changed "Format" to "Check formatting", since it technically shouldn't apply formatting in CI.
CI (and local CI)
=> [dagster-teradata] Fix formatting, and check in CI

libraries/pipes/implementations/rust/CHANGELOG.md, libraries/pipes/implementations/rust/example-dagster-pipes-rust-project/rust_processing_jobs/src/main.rs, libraries/pipes/implementations/rust/pipes.toml, libraries/pipes/implementations/rust/src/bin/pipes_tests.rs, libraries/pipes/implementations/rust/src/lib.rs
Contributes to https://github.com/dagster-io/community-integrations/issues/58
This enables the asset materialization test from the test suite. In order to get there, this also:
- Makes the `asset_key` parameter of `report_asset_materialization` & `report_asset_check` optional. This relates to https://github.com/dagster-io/community-integrations/issues/63. I'm also in favor of going with approach 2 suggested by @christeefy, but would like to tackle it separately from enabling the test now.
- Adds a function to resolve the optionally passed asset key, and corresponding error struct 
unit test & enabled test from suite
=> [pipes-rust] - enable asset materialization test

.github/workflows/quality-check-dagster-iceberg.yml, .github/workflows/template-quality-check.yml
It doesn't seem necessary to maintain a separate workflow. There isn't a docs build currently in the `community-integrations` CI, so don't even need to worry about adding a flag to install that dependency group.
Local CI
=> [dagster-iceberg] Reuse shared quality check steps

libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py
Don't hardcode the catalog name; at least for Spark, you can qualify tables using the catalog name as the database name.
This shouldn't break anything, since the base `_get_table_name` (that actually uses `database`) isn't used.
Ensure existing tests don't break; no additional functionality for now.
=> [dagster-iceberg] Set database to the catalog name

libraries/dagster-iceberg/kitchen-sink/Dockerfile, libraries/dagster-iceberg/kitchen-sink/compose.yaml, libraries/dagster-iceberg/kitchen-sink/entrypoint.sh, libraries/dagster-iceberg/kitchen-sink/hive/Dockerfile, libraries/dagster-iceberg/kitchen-sink/hive/core-site.xml, libraries/dagster-iceberg/kitchen-sink/provision.py, libraries/dagster-iceberg/kitchen-sink/spark-defaults.conf, libraries/dagster-iceberg/pyproject.toml, libraries/dagster-iceberg/uv.lock
We want a single environment that will work to test PyIceberg-based I/O managers as well as the upcoming Spark (Connect) one.
Made sure I could write to and read Iceberg using Spark Connect.
=> [dagster-iceberg] Define the `spark` package extra

libraries/dagster-iceberg/kitchen-sink/Makefile, libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
Make the existing tests work on the newly-created test environment (that should also support upcoming Spark I/O manager end-to-end tests).
Local run and GitHub Actions; unfortunately, this doesn't work on `act` as is.
=> [dagster-iceberg] Update tests to use REST catalog

libraries/dagster-iceberg/kitchen-sink/Makefile, libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
Fix/align the catalog name to be used, especially if constructing fully-qualified table names (e.g. in I/O managers).
Manual tests and CI.
=> [dagster-iceberg] Use "rest" catalog with "nyc" db

libraries/dagster-anthropic/dagster_anthropic/resource.py, libraries/dagster-gemini/dagster_gemini/resource.py, libraries/dagster-hex/dagster_hex/assets.py, libraries/dagster-iceberg/src/dagster_iceberg/_utils/__init__.py, libraries/dagster-iceberg/src/dagster_iceberg/handler.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/arrow.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/daft.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/pandas.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/polars.py, libraries/dagster-iceberg/src/dagster_iceberg/resource.py, libraries/dagster-notdiamond/dagster_notdiamond/resources.py
We removed the `experimental` decorator, which caused import errors for the use of community packages with dagster >= 1.10.0
Mostly inspection... open to suggestions.
- Updated community packages to be compatible with `dagster>=1.10.0`, which removed the experimental designation
=> update community packages to handle dagster >= 1.10

libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
Make sure existing I/O managers support partitioning properly before adding it for Spark.
Manually, local CI, CI.
I'm not confident it's reading back the data properly, but at least it's reading schema, and I can verify the data is there using Spark—which is currently more important. Will revisit this down the line.
=> [dagster-iceberg] Add partitioned Polars data test

libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Add `remote_url` that gets passed to `builder.remote()`.
Since it's configured later, it will override any `spark.remote` in `spark_config`.
Updated kitchen sink.
=> [dagster-iceberg] Support configuring Spark remote

libraries/dagster-iceberg/kitchen-sink/Makefile, libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py, libraries/dagster-iceberg/pyproject.toml, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py, libraries/dagster-iceberg/uv.lock
Remove dependency on `dagster-pyspark` that currently only provides the `spark_session_from_config()` function.
Temporarily supplied `spark.remote` via newly-added `spark_config`.
=> [dagster-iceberg] Do not require `dagster-pyspark`

libraries/dagster-obstore/dagster_obstore/azure/compute_log_manager.py, libraries/dagster-obstore/dagster_obstore/gcs/compute_log_manager.py, libraries/dagster-obstore/dagster_obstore/s3/compute_log_manager.py, libraries/dagster-obstore/pyproject.toml, libraries/dagster-obstore/uv.lock
- Since Pull Request [28652](https://github.com/dagster-io/dagster/pull/28652/files), `dagster._seven` has been replaced by `dagster_shared.seven`, we need to update the imports in `dagster-obstore`, also bump the version of dagster to latest (1.10.7).
=> [dagster-obstore] update imports to use dagster_shared and bump dagster dependency

libraries/dagster-iceberg/kitchen-sink/Makefile, libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py, libraries/dagster-iceberg/pyproject.toml, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py, libraries/dagster-iceberg/uv.lock
Implement partitioning and test static partitions (time-based partitions upcoming).
Locally using `make dev` and clicking the "Materialize" button (requires run concurrency set to `1` to prevent Spark jobs running in parallel, if materializing multiple partitions together), and via updated unit tests (doesn't require limited concurrency, since it already runs partition by partition; may need to limit concurrency when testing partition ranges in the future).
=> [dagster-iceberg] Support partitioned Spark assets

libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py
Simple organizational improvement. At some point, I would like to make the Spark tests independent of Polars, but that will require adding Spark connect support to `dagster-pyspark`—shouldn't be too bad, but not a current priority.
Manually. Also, tests still pass.
=> [dagster-iceberg] Group kitchen sink assets by lib

libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/src/dagster_iceberg/_utils/io.py, libraries/dagster-iceberg/src/dagster_iceberg/_utils/partitions.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Fix bugs wherein:
- Table wasn't being created in a partition-aware manner. Now, it implements the `partitionedBy` method as in https://iceberg.apache.org/docs/1.8.0/spark-writes/#creating-tables, but it isn't set up yet to handle time-based partitions (separate PR incoming, where I'll also test that).
- Even after creating the table with partitions, it was reading the full table. This _looked_ right before this PR, because of the sequence in which things were being run (write data for `part.0`, read data for `part.0`, overwrite the whole table with data for `part.1` because there was no partitioning, read data for `part.1`; however, when we actually enabled partitioning, the second read was returning data for `part.0` and `part.1` combined). Eventually, need to add some unit tests or …
=> [dagster-iceberg] Ensure partitioned reads, writes

libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py
Test Spark with time-based partitions (beyond the existing multi-dimensional test that includes time-based partitions).
Local runs and CI.
=> [dagster-iceberg] Test daily partitions with Spark

libraries/dagster-iceberg/kitchen-sink/kitchen_sink.py, libraries/dagster-iceberg/kitchen-sink/tests/test_e2e.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Add and test time-based and multi-partitioning support for Spark Connect Iceberg I/O manager.
Manually (see https://www.loom.com/share/42cdb702811e42348883ff79af2c5f6f?sid=46b85f26-411f-41a0-ad46-4467f7014e4d, not the `date_day` partition key in MinIO storage as opposed to just `date` that shows the partition transform*) and e2e test.
*Really need to add unit tests for these things later. 😅
=> [dagster-iceberg] Check 2D partitioning with Spark

libraries/pipes/implementations/java/build.gradle, libraries/pipes/implementations/java/settings.gradle, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/loaders/PipesCliArgsParamsLoader.java, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/loaders/PipesMappingParamsLoader.java, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/utils/PipesUtils.java, libraries/pipes/nix/shells/java/default.nix
A) change the compilation target to java17 (Apache Spark doesn't support anything newer).
B) Upgrade the mockito version (`2.7.5->4.11.0`). mockito 2.7.5 is VERY old, and fails when trying to mock newer java classes.
C) Add `PipesCliArgsParamsLoader` (setting environment variables in spark jobs can be complicated - so CLI arguments is preferred for spark workloads).
I used the resulting binary to succesfully run and test a scala-spark workload on a local spark cluster. 
change the compilation target to java17
Upgrade the mockito version (`2.7.5->4.11.0`)
Add the PipesCliArgsParamsLoader class
=> Update Java pipes to support integration with Scala-Spark

libraries/dagster-polars/CHANGELOG.md, libraries/dagster-polars/dagster_polars/io_managers/base.py, libraries/dagster-polars/dagster_polars/io_managers/type_routers.py, libraries/dagster-polars/dagster_polars/io_managers/utils.py, libraries/dagster-polars/dagster_polars/patito.py, libraries/dagster-polars/dagster_polars_tests/test_patito.py, libraries/dagster-polars/pyproject.toml, libraries/dagster-polars/uv.lock
Moving https://github.com/dagster-io/dagster/pull/28690 here. 
[Patito](https://patito.readthedocs.io/en/latest/index.html) is a minimalistic data validation library for Polars based on Pydantic. 
Since it can dynamically generate model-specific `DataFrame` and `LazyFrame` classes, we can use it for type annotations in Dagster code right now ([generics](https://github.com/dagster-io/dagster/issues/22694) are not supported by Dagster at the moment). This makes Patito a good option for seamless data validation based on type annotations (in line with the rest of `dagster-polars`), unlike `pandera`, which uses generics. 
This PR:
- allows `dagster-polars` IOManagers to work with Patito DataFrames. Eager frames are automatically validated. Lazy frames aren't (the user would have to call …
=> [dagster-polars] add Patito integration

libraries/dagster-polars/dagster_polars/patito.py, libraries/dagster-polars/dagster_polars_tests/test_patito.py
The current code always points to the metaclass name by default, which is always the same. This PR fixes this issue. 
Added a test
=> [dagster-polars] fix DagsterType name generated from patito model

libraries/dagster-contrib-gcp/CHANGELOG.md, libraries/dagster-contrib-gcp/dagster_contrib_gcp/__init__.py, libraries/dagster-contrib-gcp/dagster_contrib_gcp/cloud_run/run_launcher.py, libraries/dagster-contrib-gcp/uv.lock
Run launcher logic is errantly mutating the "job" dict. Since the daemon invokes this run launcher, and the daemon is a long-running process, multiple runs of a job will result in the `KeyError: name` 
See below for screenshots confirming behavior in deployed GCP project
Deployed changes to running GCP dagster project and validated behavior. 
Separately, `make test`
**Failure**
**Success w/ this proposed change**
=> [dagster-contrib-gcp] Bug: job dict mutation

libraries/_template/example_integration/__init__.py, libraries/dagster-anthropic/dagster_anthropic/__init__.py, libraries/dagster-chroma/dagster_chroma/__init__.py, libraries/dagster-contrib-gcp/dagster_contrib_gcp/__init__.py, libraries/dagster-evidence/dagster_evidence/__init__.py, libraries/dagster-gemini/dagster_gemini/__init__.py, libraries/dagster-hex/dagster_hex/__init__.py, libraries/dagster-hightouch/dagster_hightouch/__init__.py, libraries/dagster-iceberg/src/dagster_iceberg/__init__.py, libraries/dagster-modal/dagster_modal/__init__.py, libraries/dagster-notdiamond/dagster_notdiamond/__init__.py, libraries/dagster-obstore/dagster_obstore/__init__.py, libraries/dagster-polars/dagster_polars/__init__.py, libraries/dagster-qdrant/dagster_qdrant/__init__.py, libraries/dagster-teradata/dagster_teradata/__init__.py, libraries/dagster-weaviate/dagster_weaviate/__init__.py
Community integrations aren't versioned the same way as Dagster-maintained integrations, so we shouldn't raise a warning about the version not being what's expected.
=> Update `is_dagster_package=False` for each package

libraries/dagster-iceberg/src/dagster_iceberg/config.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/arrow.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/daft.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/pandas.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/polars.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Some of them are not showing up appropriately on the docs preview:
Also, went ahead and make everything
```
@public
@preview
```
aligned with that I see in the Dagster repo.
=> [dagster-iceberg] Ensure all APIs are in "preview"

libraries/dagster-polars/CHANGELOG.md, libraries/dagster-polars/dagster_polars/io_managers/base.py, libraries/dagster-polars/dagster_polars/io_managers/type_routers.py, libraries/dagster-polars/dagster_polars/patito.py, libraries/dagster-polars/dagster_polars_tests/conftest.py, libraries/dagster-polars/dagster_polars_tests/example.py, libraries/dagster-polars/dagster_polars_tests/test_patito.py, libraries/dagster-polars/dagster_polars_tests/test_polars_delta.py, libraries/dagster-polars/dagster_polars_tests/test_polars_parquet.py, libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers.py, libraries/dagster-polars/dagster_polars_tests/test_upath_io_managers_lazy.py, libraries/dagster-polars/pyproject.toml
This PR fixes #191 and adds a ruff rule to prevent similar errors in the future. 
It also enables import sorting for ruff which was missing. 
Existing test suite
- Fixed `ImportError` when `patito` is not installed
=> [dagster-polars] fix ImportError with patito and ensure optional deps are not imported at top level

libraries/dagster-iceberg/src/dagster_iceberg/handler.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/spark.py
Some classes included in the documentation are currently missing docstrings.
Built docs locally:
=> [dagster-iceberg] Add API docs for classes without

libraries/dagster-evidence/dagster_evidence/__init__.py, libraries/dagster-evidence/dagster_evidence/resource.py, libraries/dagster-evidence/dagster_evidence_tests/test_evidence_resource.py
Include a resource for the Evidence integration.
**Basic**
```python
import dagster as dg
from dagster_evidence import EvidenceResource
@dg.asset
def evidence_application(evidence: EvidenceResource):
evidence.build()
evidence_resource = EvidenceResource(
project_path="/path/to/evidence/project",
deploy_command="your-deploy-command",
)
defs = dg.Definitions(
assets=[evidence_application],
resources={"evidence": evidence_resource}
)
```
-
=> Evidence resource

libraries/pipes/implementations/java/build.gradle, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/PipesContext.java, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/PipesContextImpl.java, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/PipesContextInstance.java, libraries/pipes/implementations/java/src/main/java/io/dagster/pipes/PipesSession.java, libraries/pipes/implementations/java/tests/conftest.py, libraries/pipes/implementations/java/tests/test_pipes.py
fixes https://github.com/dagster-io/community-integrations/issues/221
- the jar building does not include the dependencies anymore
- in order to run the MainTest class in the tests the application plugin is used to build a start script and libs directory
- the test dependencies are declared separately now so that a user of the library doesn't depend on them
- mockito was needed in the library to create a mock class. to remove mockito from the library the PipesContext was converted to an interface with an empty implementation instead of the mockito mock
https://github.com/dagster-io/community-integrations/issues/221
`uv run pytest`
=> [pipes-java] fix JAR building and test dependencies

libraries/dagster-polars/CHANGELOG.md, libraries/dagster-polars/dagster_polars/io_managers/parquet.py
https://github.com/dagster-io/community-integrations/issues/219
https://github.com/dagster-io/dagster/issues/28633
related issues, since it's a dictionary passed in where only string values are allowed, the solution was to remove that key from a copy of the dictionary. Should be okay to use `del` on a key for a value that is a collection if a copy is made without affecting at the call site.
- I did not test, I will do this, I may need help?
=> [dagster-polars] fix: sanitize config passed to polars.scan_parquet

.github/workflows/quality-check-dagster-apprise.yml, libraries/dagster-apprise/CHANGELOG.md, libraries/dagster-apprise/Makefile, libraries/dagster-apprise/README.md, libraries/dagster-apprise/dagster_apprise/__init__.py, libraries/dagster-apprise/dagster_apprise/_utils.py, libraries/dagster-apprise/dagster_apprise/components.py, libraries/dagster-apprise/dagster_apprise/hooks.py, libraries/dagster-apprise/dagster_apprise/resource.py, libraries/dagster-apprise/dagster_apprise_tests/test_component_sensor.py, libraries/dagster-apprise/dagster_apprise_tests/test_comprehensive_urls.py, libraries/dagster-apprise/dagster_apprise_tests/test_edge_cases.py, libraries/dagster-apprise/dagster_apprise_tests/test_hooks.py, libraries/dagster-apprise/dagster_apprise_tests/test_resource.py, libraries/dagster-apprise/dagster_apprise_tests/test_utils.py, libraries/dagster-apprise/pyproject.toml, libraries/dagster-apprise/uv.lock
When running jobs, I found myself wanting to find a way to have better notifications built into jobs both for checkpoints and for successes/failures. While I recognize Dagster+ has some of these notifications tightly integrated, I currently have no need or budget for Dagster+, so I thought I would integrate [Apprise](https://github.com/caronc/apprise) (lightweight notification python package) to have some options for smaller Dagster setups. Let me know if there are any changes that should be made!
There are currently unit tests that cover the majority of the code. 
=> New integration: dagster-apprise

libraries/dagster-iceberg/CHANGELOG.md, libraries/dagster-iceberg/src/dagster_iceberg/_utils/io.py, libraries/dagster-iceberg/src/dagster_iceberg/handler.py, libraries/dagster-iceberg/src/dagster_iceberg/io_manager/base.py, libraries/dagster-iceberg/tests/_utils/test_io.py, libraries/dagster-iceberg/tests/conftest.py, libraries/dagster-iceberg/tests/io_managers/test_polars_io_manager.py, libraries/dagster-iceberg/tests/test_handler.py
Fixes #231 
This PR adds support for append mode to the Iceberg IO manager. The write mode can be set in asset definition metadata or at runtime via output metadata, using the key `write_mode`. Valid options are `append` or `overwrite`. 
Added a number of unit tests to show append mode adds new values on top of existing values. Added unit tests for overwrite mode as well to highlight the difference in functionality.
Adding a write mode kind of led to a proliferation of tests... I initially implemented them with `@pytest.parametrize`, but found it to be pretty hard to read, so I switched to just having a test utility method. There's a lot of repetition in the tests already, if folks are open to it I'd be willing to try to bootstrap some testing infrastructure in a future PR.
I initially …
=> [dagster-iceberg] Add append mode support
